server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
# telling the built-in Eureka Client not to register with ‘itself'
# because our application should be acting as a server.
